### PR TITLE
+Added new short fade transitions

### PR DESCRIPTION
**Pull request by washaweb**
+Added delay-{XX}{m}s class
+Added duration-{XX}{m}s class
~Updated readme

### CODE REVIEW

**Comment by washaweb** [comment]
Hi, this is my first contribution to a project, so please be indulgent.

**Comment by daneden** [comment]
Hey @washaweb! Thanks for the PR and sorry for the delay (the project is sadly lower on my list of priorities than it once was).

Would you mind providing a Codepen demonstrating the new changes?

**Comment by eltonmesquita** [comment]
@washaweb, any news on the pen?

**Comment by eltonmesquita** [comment]
Closing it as it's stale. @washaweb , feel free to reopen it in case you've got a pen to show us.

**Pull request closed without merging**
