### PR TITLE
Experimental - Add Namespace

### PR DESCRIPTION
**Pull request by WarenGonzaga**
Hello @daneden and @eltonmesquita here's the feature request for the namespace.. I add it to the base sass file and let me know if necessary to do the same with individual animations. Thanks!

### CODE REVIEW

**Comment by daneden** [comment]
We probably want to add namespaces to all the animate.css classes, and find a way to automate it/allow users to specify their own namespace in the config file (with a default, of course).

**Comment by WarenGonzaga** [comment]
@daneden yup! Will do that.. will update this one... it is only a base of our experimental feature. This one should be available on v4 of animate.css let's leave the 3.7.0 untouched except some dev-dependencies updates.

**Comment by eltonmesquita** [comment]
I think Postcss can do it easily. Maybe [postcss-prefixer](https://github.com/marceloucker/postcss-prefixer) can take care of it. But first it's better to solve #836 first then solve this one. I might do it by the weekend if I get enough time.

**Comment by eltonmesquita** [comment]
I'll start moving the `dev` branch to Rollup, so I'll close this as it's not way we want this to be done, alright?
Thanks for the effort!

**Comment by WarenGonzaga** [comment]
Alright awesome! Page me for any updates...

**Pull request closed without merging**
