### PR TITLE
add yarn in readme.md

### PR DESCRIPTION
**Pull request by ahmetozantekin**
Added yarn as an install method in readme file.

### CODE REVIEW

**Comment by WarenGonzaga** [comment]
what do you think @eltonmesquita

**Comment by eltonmesquita** [comment]
Although it doesn't hurt to add yarn, I don't think it's necessary at all as npm and yarn are interchangeable. But I'm open to it. What do you think @WarenGonzaga ?

**Comment by WarenGonzaga** [comment]
@eltonmesquita base on this https://scotch.io/@brian_kimo/npm-vs-yarn I think we should add options to our users to select which they want to use between NPN or YARN.

**Comment by eltonmesquita** [comment]
Alright. Merging it.

**Pull request merged**
