### PR TITLE
Hot Fix - Replace Deprecated Gulp-Util

### PR DESCRIPTION
**Pull request by WarenGonzaga**
When updating the dev-dependencies I saw that gutil is now deprecated that's why replace it with other npm module based on this blog as suggested https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5 I just replace the log and add color in it. This hotfix would be available on v4 of animate.css

### CODE REVIEW

**Comment by WarenGonzaga** [comment]
@eltonmesquita and @daneden please review this

**Comment by eltonmesquita** [comment]
Hey @WarenGonzaga . Do you think we still need to update this as we're moving away from Gulp? As usually, unfortunately, I've got little time available and would like to focus my efforts on the new version/build system.
By the way, I'd love some feedback on #900 and maybe some PRs with improvements on the build system.

**Comment by WarenGonzaga** [comment]
What we are using aside Gulp? @eltonmesquita ?

**Comment by eltonmesquita** [comment]
Just npx + postcss @WarenGonzaga. It already does everything Gulp does + adds prefixes to all classes with half the code.
Please see #900. I'd love some feedback about it!

**Comment by eltonmesquita** [comment]
I'm shutting this as all efforts will be focused on v4.

**Comment by WarenGonzaga** [comment]
@eltonmesquita awesome!

**Pull request closed without merging**
