### PR TITLE
Added fading diagonal animations

### PR DESCRIPTION
**Pull request by vaibhav111tandon**
Added fading animations through diagonals for both fadeIn and fadeOut
> TopLeft
> TopRight
> BottomLeft
> BottomRight

### CODE REVIEW

**Comment by eltonmesquita** [comment]
Please see https://github.com/daneden/animate.css#contributing and update this PR.
Thanks.

**Comment by vaibhav111tandon** [comment]
Demo:
https://codepen.io/Vaibhav119/full/yWoYJW
and classes are in camelCase

**Comment by WarenGonzaga** [comment]
@vaibhav111tandon these are good... @eltonmesquita we can add these animations on v4

**Comment by eltonmesquita** [comment]
Hey @vaibhav111tandon , thanks for the PR!
Although they are totally consistent with the fade entrances/exit, they didn't feel "natural" to me. This feel makes me ask:
Do we really need diagonal entrances/exits?
I would love to hear some opinions here...

**Comment by vaibhav111tandon** [comment]
Sir,
it is your library, therefore it is totally your decision to merge this request or not, if you don't find it appropriate, it's totally ok.

**Comment by eltonmesquita** [comment]
@vaibhav111tandon, this is not my library, it's an open source library :smile: 

There were many times people showed me here that my opinion was not the best for the library and we ended up merging the PR. And as I asked before, I'm not sure, so I need some feedback to make a decision. 

Any thoughts about the question I've done?

**Comment by WarenGonzaga** [comment]
@vaibhav111tandon fyi... this is not elton's library it is an open source library there so many contributor here including me.. so that...  it is a public library for everyone... for me... @eltonmesquita we can add this animations as extras or misc since it is not necessary in any animation (kind of optional animation for extra spices).

**Comment by vaibhav111tandon** [comment]
@WarenGonzaga I think adding them as misc. will be good

**Comment by eltonmesquita** [comment]
Sorry for the delay, but I've changed my mind and it'll get released on v4!

You can see a preview here: https://codepen.io/eltonmesquita/full/agrYzj

**Comment by eltonmesquita** [comment]
BTW it's merged on the `dev` as you can see on 793b0ffc

**Comment by vaibhav111tandon** [comment]
Thank you very much 😊

**Comment by WarenGonzaga** [comment]
@eltonmesquita @vaibhav111tandon good job guys... see you on V4

**Comment by WarenGonzaga** [comment]
@eltonmesquita kindly close this since it is added in v4
current development progress at #1029

**Comment by WarenGonzaga** [comment]
@daneden kindly review this and close if necessary...

**Pull request closed without merging**
