### PR TITLE
Update gulp to version 4.0.2 and update js-yaml to --depth 4

### LINKED ISSUE #938: Issue installing with Node v12 (fsevents)
I believe that `fsevents` is only used for MacOS so this issue may only be on that OS.

```bash
# on latest version of Node.js
$ node -v
> v12.3.1
$ npm -v
> 6.9.0
```

## Steps to Reproduce

`package.json` contents:
```json
{
  "private": true,
  "dependencies": {
    "animate.css": "^3.7.1"
  }
}
```

Then, using latest Node 12.3.1 on MacOS, run `npm install`.

## Output

```bash
$ npm install

node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.4/fse-v1.2.4-node-v72-darwin-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.4 and node@12.3.1 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)

[... continues with a long log of syntax errors and deprecation notices ...]
```

The issue may lie with a dependency and not this project. If that's the case, I apologize for opening an issue here. I wasn't able to track down what the fix is. I do see `fsevents@1.2.4` in the shrinkwrap for this package, though.

### PR DESCRIPTION
**Pull request by Mackignacio**
- Fix #938

### CODE REVIEW

**Comment by WarenGonzaga** [comment]
Hi, @Mackignacio we no longer need the gulp updates for building animate.css as we migrate to another software development tool like postcss...

**Comment by WarenGonzaga** [comment]
@eltonmesquita please review this pull request and let me know what you think thanks! Also add proper label... ;)

**Comment by PetrSnobelt** [comment]
Consider https://dependabot.com for keeping dependencies up to date

**Comment by fitztrev** [comment]
@Mackignacio I don't think it's the upgrade of Gulp that fixes my issue (#938), but rather just rebuilding of the shrinkwrap.

**Comment by Mackignacio** [comment]
@fitztrev  Updating gulp is also good for staying up to date. As for my end its working and I don't have the issue anymore when I'm running `npm i` on my machine.  I think the problem is not on the shrinkwrap but else where.

**Comment by Mackignacio** [comment]
@WarenGonzaga  I think we can just wait for 4.0 to be released then if this issue persist we can have another looked for it. I will be closing this PR thank you for the info.

**Comment by WarenGonzaga** [comment]
@Mackignacio cool... gulp will not available anymore in v4 of animate.css ;)

**Pull request closed without merging**
