### PR TITLE
#537 will-change performance improvements

### PR DESCRIPTION
**Pull request by klopfdreh**

### CODE REVIEW

**Comment by tnga** [comment]
Please, why not add `will-change` declaration directly at the begin of animations implementation like you have done with it for `auto` value at the end of considered implementions. For an example with `flipInX`:

```css
 @keyframes flipInX {
  from {

    will-change: transform, opacity, animation-timing-function; //Browser indication For performance improvements

    transform: perspective(400px) rotate3d(1, 0, 0, 90deg);
    animation-timing-function: ease-in;
    opacity: 0;
  }

  40% {
    transform: perspective(400px) rotate3d(1, 0, 0, -20deg);
    animation-timing-function: ease-in;
  }

  60% {
    transform: perspective(400px) rotate3d(1, 0, 0, 10deg);
    opacity: 1;
  }

  80% {
    transform: perspective(400px) rotate3d(1, 0, 0, -5deg);
  }

  to {
    will-change: auto; //reset For performance improvements
    transform: perspective(400px);
  }
}
```

**Comment by klopfdreh** [comment]
Hi Tindo,

as mentioned here https://github.com/daneden/animate.css/issues/537#issuecomment-186105273 the browser needs a bit time to ramp up the performance optimizations, but they are optional. So if you put it in the animation it can cause to not speed up the animation and even do nothing at all.

**Comment by tnga** [comment]
Thank for precision! I just want to understand, so it is also the reason of your mentioned tips to use javaScript to add animation class after the new *<animation-name>Hint* class depending of (DOM Events). For my point of view this isn't really attractive to use, cause generally when using a library it's because once want to make things without more efforts. The actual animate.css usage way it attractive because it's independent and it is not (especially for simple or primary usage) necessary to use javaScript.

However like you say this improvement will be optionnal if it is merged. But i thing it will be better if there can be a way to have something like:
```css
.fadeIn {
 will-change: opacity; /*Browser indication For performance improvements*/
  animation-name: fadeIn;
}
```
So that have the improvement and skip the actual usage way.

**Comment by klopfdreh** [comment]
Hi Tindo,

the code block you mentioned there will only have a minimal to no effect, because the animation is started directly when the class is added to a container (because it defines the animation-name) and the browser will not have the time to improve the performance. For animations started directly when you render the page, I would recommend not to use these hints.

For animations started via script (I think that most of them will be applied this way), you can add this hints. Think about when to use animations. In most cases you write something like on('click') or on('hover') via script and apply a class - right?

So you can use the framework like before and ignore this change.

**Comment by klopfdreh** [comment]
Just one thing I forgot: If you want to use the performance improvements onload you can use set timeout.

**Comment by eltonmesquita** [comment]
Closing this, see reasons on #537.

**Pull request closed without merging**
