### PR TITLE
New animation: Squash

### PR DESCRIPTION
**Pull request by FelipeMartinin**
Inspired in the first animation principle, Squash & Stretch, follow a new animation proposal, just called Squash:

http://codepen.io/FelipeMartinin/pen/dYXabb

### CODE REVIEW

**Comment by procodeing** [comment]
I like it, but it is a bit extreme at the beginning, but otherwise, It's a great idea.

**Comment by FelipeMartinin** [comment]
Hello procodeing, thanks for the thoughts. Can you do an improvement as a suggestion using my codepen demo as a base?

**Comment by procodeing** [comment]
Already did! http://codepen.io/procodeing/pen/LpRYqe

**Comment by procodeing** [comment]
Sure!

**Comment by FelipeMartinin** [comment]
Nice! Thanks in advance! :D

**Comment by daneden** [comment]
This is a little aggressive with a lot going on. How does this animation look applied to, say, a text-heavy form? Think about the use case first and try experimenting with something simpler :)

**Comment by emanwebdev** [comment]
Gee!!! great!  your animate's becooooming just GREAT!  

thanks guys !

**Comment by procodeing** [comment]
Hey, sorry I've been gone for so long. Anyway, [here](http://codepen.io/procodeing/details/dMPaQd/) is a bit of an "eased up" version, using the original animation as a base. If it needs a bit more easing, a ratio would be useful.

**Comment by eltonmesquita** [comment]
I'll close this as there was no improvement in much time. Feel free to send a PR with improvements if you wish.

**Pull request closed without merging**
