### PR TITLE
v4 release

### PR DESCRIPTION
**Pull request by eltonmesquita**
This PR updates Animate.css with the following:
* New animations:
    * ShakeY
    * fadeInTopLeft
    * fadeInTopRight
    * fadeInBottomLeft
    * fadeInBottomRight
    * fadeOutTopLeft
    * fadeOutTopRight
    * fadeOutBottomRight
    * fadeOutBottomLeft
    * lightSpeedInRight
    * lightSpeedInLeft
    * lightSpeedOutRight
    * lightSpeedOutLeft
    * backOutDown
    * backOutLeft
    * backOutRight
    * backOutUp
    * Bouncing entrances
    * bounceIn
    * bounceInDown
    * bounceInLeft
    * bounceInRight
    * bounceInUp
* Improved animations
* Adds prefix `animate__` to all classes, avoiding CSS class clashes
* Adds new utility classes
* Adds CSS custom properties support
* Leaner and up-to-date dependencies build system
* Updates demo-website layout
* Add and improve documentation and build system to the demo-website

### CODE REVIEW

**Comment by daneden** [comment]
FYI the version in the compiled files still says 3.7.2—will that change when the tag is at v4?

**Comment by daneden** [comment]
Ah, I guess this is pulled from package.json.

**Comment by eltonmesquita** [comment]
> Ah, I guess this is pulled from package.json.

Yeah, that'll change when publishing.

**Comment by WarenGonzaga** [comment]
Can't wait to release this! Do we have a target date? @daneden after the release are you going to move this repo into the organization?

**Comment by eltonmesquita** [comment]
@WarenGonzaga , the plan is to do this still today. We're working on it right now!
About the organization, I that'll be done today too :D

**Comment by WarenGonzaga** [comment]
@eltonmesquita really? Since we are now in organization I created a Facebook page... can I add it to the readme? I added you guys on Facebook too.

**Comment by daneden** [comment]
@WarenGonzaga I don’t know if we need/want a FB page right now! I think keeping things simple is one of the broader goals of the v4 release and the org change; let’s stick to GitHub for the time being 😄

**Comment by WarenGonzaga** [comment]
@daneden got it...

**Pull request merged**
