### PR TITLE
added new animation style - advertise

### PR DESCRIPTION
**Pull request by Priyanka-Veeranna**
I have added a simple animation style, that can be used for flashy advertising messages/headlines.

A simple demo of the same can be found on codepen here 

http://codepen.io/PriyankaCodes/pen/wGRqqO/

### CODE REVIEW

**Comment by tnga** [comment]
Awesome :smile: . You dont have to edit `animate.css` file directly ; you need to improve it in `source/attention_seekers/` directory and then use gulp to compile new `animate.css` production. Just look how other animations are referenced :wink: . Why **advertise**, think is too formel for animation name; however it's just my point of view.

**Comment by Priyanka-Veeranna** [comment]
Okie...have made the changes; compiled animate.css using gulp and added a new file under 'attention_seekers' folder. 

Yeah, I agree, the name is a bit formal; but i'm so bad at naming, esp coming up with catchy, creative ones :) Any suggestions will be welcome and will change name in the code as well ;)

**Comment by tnga** [comment]
Ok :+1: ! Now i'm worry about the fact that you have up to 1,809 deleted lines for 76 inserted lines. Considered you have only add feature, this status have to be little proportional. Since `diff` can't show on my browser i can really have an overview to know if it's normal; i will take a look locally after. Therefore, make sure every thing is well done :wink: .

For my name's suggestion, ... maybe... **heed** or **parade** ? As you have been inspired to do the animation, you will be inspired for the name; so if *"advertise"* will be finally your choice ...

**Comment by Priyanka-Veeranna** [comment]
"Parade" seem apt. I'll go with Parade :)

Those many deletions confused me as well. I double checked to see if everything was alright after I noticed that. Everything was fine. I'm thinking it may because of this Git notice I got about LF and CRLF Or may be because I was making the changes on a different branch and merged it with the master branch before pushing it up to origin.

thanks.

**Comment by eltonmesquita** [comment]
I think it's a bit flashy and gratuitous. There isn't a clear intention for the animation.
Sorry but I'll have to refuse it.

**Pull request closed without merging**
