### PR TITLE
#479 fixes bounceIn animations for iOS devices

### PR DESCRIPTION
**Pull request by klopfdreh**

### CODE REVIEW

**Comment by Johnathan** [comment]
Think I'm getting the same issue with slideInUp/Down.

**Comment by cliffhall** [comment]
I really wanted this to work, but tried it on my iPhone 6s and still no dice. With the old code, I was able to get some screens to work, but at the moment, on one screen, it refuses to work. It has no other conflicting animations going on, and is built similar to other pages that work. Hopefully I'll fix it, but if not, the problem page is 'Contact' (link at bottom of all pages) on [https://page-fight.com](https://page-fight.com)

**Comment by klopfdreh** [comment]
That is strange, because I tested it on iOS Safari and for me this change causing the Animation to work. I tested Safari only.

**Comment by janstieler** [comment]
The problem is still on iOS 10 Safari.

**Comment by klopfdreh** [comment]
Did you took the changes from this PR or did you use the main repo - this fix isn't integrated, yet.

**Comment by christru** [comment]
I took the changes from pull request and was still having an issue when testing in browserstack :(

**Comment by eltonmesquita** [comment]
I'm closing this as I don't think we shouldn't have to try to "fix" browser bugs in an animation library in 2017. Also as cited above this doesn't seem to fix all the issues.

Ps.: iOS Safari 9-10 does seem to have some issues with transforms (and clip-path, and lots more stuff). I'm still doing some research here, would be glad if someone pointed to an article or something more detailed about this.

**Pull request closed without merging**
