### PR TITLE
Onhover class name added

### PR DESCRIPTION
**Pull request by SebYeates**
Hello, 

This is my first pull request so hope it's worked. 

I've created a class for all the animations to work when the mouse is hovering over. It's a simple ":hover" in the CSS after the class name. After working with some people who just understand adding in class names in the HTML, I had an idea of adding this in to save them time. 

 Example of "onhover-[animation name]" below. 

```html
<h1 class="onhover-bounce">This is a test</h1>
```

I've updated the read me also to show the hover option. 

look forward to talking. Kind regards
Sebastian Yeates

### CODE REVIEW

**Comment by WarenGonzaga** [comment]
Hi there, do you have codepen for this? So we can check if it is really effective or kind of bloat features of animate.css ;)

**Comment by SebYeates** [comment]
Hi, 
Here is the code pen: https://codepen.io/yeatessa/pen/zbRemL

It's nothing complicated like I said before, just adding in ":hover" after the class name then the animation to keep it simple as possible. Could be seen as a bloat feature but up to you to decide.

Any questions let me know. Thanks :)

**Comment by WarenGonzaga** [comment]
Cool! I see it has potential... @eltonmesquita and @daneden we can add this on the biggest update of animate.css ;)

**Comment by eltonmesquita** [comment]
I'll review this and think about this feature a little bit.

**Comment by eltonmesquita** [comment]
Sorry for the late answer. First of all, your commit is empty. There's no file change besides other people commits. Second, although it does make sense, I think this is so easily abused that it might have a negative effect on usability.

The idea is great indeed, and I'm really glad that you took your time and proposed it but I'll have to reject it based on the above fact.

Thanks for the PR!

**Pull request closed without merging**
