### PR TITLE
Added a featherFloatIn and featherFloatOut animation to function in a…

### PR DESCRIPTION
**Pull request by TieCu**
…nimate.css

### CODE REVIEW

**Comment by eltonmesquita** [comment]
Please see [this](https://github.com/daneden/animate.css/blob/master/README.md#contributing)

**Comment by WarenGonzaga** [comment]
dear author, you have to provide us a codepen demo of it.

**Comment by eltonmesquita** [comment]
I'm considering closing this as there's no answer to what was requested.

**Comment by WarenGonzaga** [comment]
yeah I think I can do it... and check if it is fit to animate.css let me work on this.

**Pull request closed without merging**
