### PR TITLE
Move files to dist directory

### LINKED ISSUE #501: Bower - Use dist/ for final product
Bower lightly hints at using `dist/` for the final package distributables. Many other popular packages do this as well.

The advantage of doing this is to assist in streamlining the build process.

Developers can just easily copy (or link) out the `bower_components/<package_name>/dist/` directory (e.g. within express, as `app.use('animate', express.static('bower_components/animate-css/dist/'));`) rather than cherry-picking each distributable within packages.

### PR DESCRIPTION
**Pull request by daneden**
Resolves #501.

### CODE REVIEW

**Comment by jnovack** [comment]
This is a breaking change for some people who link directly to `bower_components/animate.css/animate.css`, at least a minor version change and a warning might be warranted.

**Comment by jnovack** [comment]
So close, yet so far...

**Comment by daneden** [comment]
@jnovack maintaining OSS is hard! I’ll work on this again, uh, soon. Maybe.

**Comment by eltonmesquita** [comment]
Hey @daneden, don't you need help maintaining animate.css? There are lots of open issues that could be closed or at least properly tagged and organized. I'd love to help. DM on [Twitter](https://twitter.com/eltonfmesquita) if you want to talk about it :D
Thanks.

**Comment by eltonmesquita** [comment]
Closing this as bower is being killed anyway. Please see #758.

**Pull request closed without merging**
