### PR TITLE
Animate.css Builder Web Version (Fixed)

### PR DESCRIPTION
**Pull request by WarenGonzaga**
I fix the conflict in the code on index.html from this pull request #622 made by https://github.com/Igorxp5

### CODE REVIEW

**Comment by Igorxp5** [comment]
I've tested, it's working :)

**Comment by WarenGonzaga** [comment]
Yeah! Thanks for the improvement... let's wait for Dan Eden to review this...

**Comment by WarenGonzaga** [comment]
Are we gonna add this stuff to the v4? @eltonmesquita

**Comment by eltonmesquita** [comment]
At the moment I'm focused on the v4 work, but as soon as I finish it, I'll take my time, review it and decide if this will get merged.
Sorry for the loooong delay...

**Comment by eltonmesquita** [comment]
I feel like the dev world changed so much from this PR to now that I ask myself if it would still be relevant to have such a feature for making a custom build. What do you think?

**Comment by eltonmesquita** [comment]
Thanks everyone that put some work on this PR, but unfortunately I'll close this as the dev world just changed too much and there'll be some changes on the demo site that would make this a hard fit.

**Pull request closed without merging**
