### PR TITLE
replaced 0% keyframes with 'from' keyword

### PR DESCRIPTION
**Pull request by mesge**
There's an [open issue](https://github.com/yui/yuicompressor/issues/113) with YUI-compressor where `0%` is optimised to `0`. The combination of yui-compressor and animate.min.css/animate.css causes most of the animations to break. 

Unfortunately, YUI wait a long time between releases and yui-compressor is one of the most popular css compressors for Rails and other frameworks. It's [been suggested](https://github.com/yui/yuicompressor/issues/113#issuecomment-40824428) that `0%` is replaced with the `from` keyword until YUI release a fix.

Good news is that `from` and `0%` are interchangeable with keyframe animations, and this pull-request causes yui-compressor to play nice.

### CODE REVIEW

**Comment by daneden** [comment]
Nice catch. Mind running Grunt to build the compiled CSS, too?

**Comment by mesge** [comment]
Thanks. I've just made that addition.

**Comment by procodeing** [comment]
@daneden Wait, if we are changing the 0% to from, why don't we keep consistency and change all of the 100% to "to"? If I am not mistaken, all of the animations have a 100% for whatever reason that was (besides performance and support), I am pretty sure that to and 100% are interchangeable just like from and 0%. Plus, it's shorter.

**Comment by mesge** [comment]
Hey @procodeing, that's a valid point.

**Pull request merged**
