### PR TITLE
Switch to Sass

### PR DESCRIPTION
**Pull request by daneden**
I’m working through adding some Sass functionality to Animate.css and using it as the primary language going forward.

We’ll use this PR to discuss development, potential features, and track progress.

Wishlist item(s) I’d like to explore before merging to master:

[ ] Config options for transformations[^1]

[^1]: In other words, adding options for relative vs. absolute transformations (relative to the transformed element vs. fixed, absolute transformation values), and adding some sort of scale for absolute transformations (small, medium, large, extra large, etc.)

### CODE REVIEW

**Comment by daneden** [comment]
Note to think about package releases conflicting with custom builds for the 4.0/Sass release (first brought up in #333)

**Comment by procodeing** [comment]
@daneden Please keep the orignal animate.css, for those of us that are not familier with Sass.

**Comment by procodeing** [comment]
I will try to learn it over the weekend though

**Comment by eltonmesquita** [comment]
Don't worry about this @procodeing, SASS always generates a css file, there's no need to use it if you don't want to, although you'll probably gain a lot learning any pre-processor.

**Comment by procodeing** [comment]
ok @eltonmesquita , Thanks. I will aslo try and learn SASS and SCSS over the weekend.

**Comment by procodeing** [comment]
@eltonmesquita Ok i've learned it.

**Comment by procodeing** [comment]
@daneden Are we talking Sass, or SCSS

**Comment by procodeing** [comment]
Hey @daneden , I have a pull request that adds the jello to sass, with the occording scss files, as well as the inports.

**Comment by mswanson** [comment]
Hey @daneden  anything I can do to help with porting this over? Let me know, very interested in using the SASS version.

**Comment by gpapin** [comment]
hi @daneden, I'm really looking forward the sass support, any update on this ?

**Comment by augbog** [comment]
:+1: also looking forward to this port.

**Comment by dlcardozo** [comment]
I made a port to sass of current animations, if you want I can add that.

**Comment by noahbuscher** [comment]
@daneden Hey, Dan! Any update on the sass support? :grimacing:

**Comment by procodeing** [comment]
@dlcardozo hey, do you have a pull request for that? that could be useful!

**Comment by jenslind** [comment]
I also made a port of this to scss which adds the used animations automagically (a bit experimental). Happy to help out if wanted.

**Comment by Jacco-V** [comment]
Any word on the progress of this effort?

**Comment by AndresOchoaS** [comment]
I think it would be ideal to add autoprefixer to this version. Support from browsers changes very often, so it's best to let the autoprefixer take care of it. [See more](https://github.com/postcss/autoprefixer)

**Comment by tomsommer** [comment]
SCSS would be great, but autoprefixer is usually handled globally, so no real reason to add this.

**Comment by arcanedev-maroc** [comment]
Yes, there is no need to add prefixes thanks to [PostCSS](https://github.com/postcss/postcss) and https://github.com/postcss/autoprefixer.

**Comment by daneden** [comment]
So it turns out the landscape for web development changes a lot in 4(!) years. With fresh eyes, I think what we'd want from a major rewrite today is to use CSS custom properties to get the kinds of things I'd have liked to get with SCSS.

I’m closing this based on the assumption that regular, modern CSS now gives us most of what we'd want from SCSS, but open to suggestions about what a major rewrite should offer.

**Comment by daneden** [comment]
I impulsively made a call here and am now reconsidering. I'm still open to community suggestions about what we'd like to see in a major version of Animate.css.

Open source is hard! Thanks everyone (**especially** @eltonmesquita!) for your contributions and patience.

**Comment by eltonmesquita** [comment]
No need to thanks @daneden ;D. TBH, I think that the considerations you showed when you've sent this PR are still valid. As far as I can say SCSS is still the most used and known pre-processor out there. Although there are some Sass features that could make things easier, I do like the way you kept things simple and easy to understand even for beginners. I vote for this simplicity!

Something that's being etching my ears is how we'll deal with this outdated branch. It's not an easy merge, at all. I still don't have a good plan to merge these branches without a massive work and unfortunately ReaLife have not made easy to get proper time to think in details about this. Any suggestion?

In the next weeks I'll have lots of free time, so I'll be able to put things in action.

**Comment by daneden** [comment]
@eltonmesquita and I chatted a bit about this, and along with difficulties to merge this old branch, I think it's safe to say that we can abandon a move to SCSS. The main reasons to do so in the first place were:

- **Custom namespaces.** We've had a few folks needing a safe namespace for Animate.css classes, but we think this need is borne more out of needing _any_ safe namespace than necessarily needing a _custom_ namespace. This is something we can change in a 4.0 version _without_ SCSS.
- **Variables/customisations.** With the addition of custom properties in CSS, we can now do this without the use of a CSS preprocessor (and even have dynamic variables that can be changed with JS!)

In addition to the above, I'm confident that using modern, plain CSS is a much more future-proof option than switching now to Sass and then eventually (likely) once more back to plain CSS.

**Comment by sp90** [comment]
@daneden I guess the reason for having a Scss version was so that it could toggle the need of keyframes so you don't bloat your project with all the keyframes when they're not needed, but I understand your idea of having it in plain and respect your choice 👍

**Comment by daneden** [comment]
@sp90 I figured that with [postcss](https://github.com/postcss/postcss-import) people could still do this. I do this with my personal site, using `@import "file.css"` to compile to a single stylesheet.

**Comment by JayHoltslander** [comment]
Hello. I ended up here after searching for "Animate.css Sass"

> I think it's safe to say that we can abandon a move to SCSS

☹️

**Comment by zedjr** [comment]
Is there a way to use version 4 in my sass files rather than put the code in my html. I know of extend but i know that can and will have adverse effects. Is there another way?

**Comment by eltonmesquita** [comment]
SASS supports CSS imports, so you can just import the files you need directly from the animate.css project.

**Comment by zedjr** [comment]
yes but how do you use animate css library without using @extend. Or must i use extend and if so will it be ok using extend with this library. I have seen other libraries that claim it is ok using extend with their css library.

**Comment by eltonmesquita** [comment]
There should be no problem using extends or just importing the files and using the file names directly in the HTML. You could also create a thin wrapper around it so you can even switch the provided CSS variables through SASS. There's no recommended way for using the library alongside SASS, do what works best for you.

If you need more help with this, please use stackoverflow or the likes as this is an issue tracker that is used to report bugs and improvements. You won't get much help about usage around here.

**Pull request closed without merging**
