### PR TITLE
Added an animation called stretch

### PR DESCRIPTION
**Pull request by CodingKid124**
Added an animation called stretch (code all the way at the bottom)

### CODE REVIEW

**Comment by WarenGonzaga** [comment]
Do you any preview for that animation? Any codepen link for preview?

**Comment by eltonmesquita** [comment]
As @WarenGonzaga noted, we need a pen with the animation so we can evaluate it, as noted on readme:
>  I only have two rules for submitting a pull request: match the naming convention (camelCase, categorised [fades, bounces, etc]) **and let us see a demo of submitted animations in a pen**. That last one is important.

**Comment by WarenGonzaga** [comment]
Please provide any codepen preview for your animation. Sign up here if you don't have account codepen.io

**Comment by eltonmesquita** [comment]
Any news on this @CodingKid124 ?

**Comment by WarenGonzaga** [comment]
I think he is not active ?

**Comment by eltonmesquita** [comment]
I'm closing this as it's stale. Fell free to reopen it **if you have a live version to the animation.***

**Comment by WarenGonzaga** [comment]
What if @eltonmesquita let's work on it?

**Comment by eltonmesquita** [comment]
Sorry, but I'm really focusing on pushing animate.css forwards, get the new - v3.6.0 - version live and get in the work for releasing v4.0.0.
If there's a live version for anyone to judge, I might consider it but the rule is clear and I can't merge anything without seeing it live.

Ok?

**Comment by dk574** [comment]
Got it. Sounds great to me :)

**Pull request closed without merging**
