### PR TITLE
HTTPS relevant links on README

### PR DESCRIPTION
**Pull request by coliff**
prevents HTTP redirects

### CODE REVIEW

**Comment by coliff** [comment]
@WarenGonzaga what do you mean?

**Comment by WarenGonzaga** [comment]
@coliff don't just add either http or http you could use "://" only to make it dynamic...

**Comment by coliff** [comment]
Protocol-less URLs are an anti-pattern (bad practise). It also means you wouldn't be able to Ctrl+click them in a code editor to launch the website in a browser.

Those URLs are all HTTPS-only so making the URLs explicitly HTTPS saves a redirect.

**Comment by WarenGonzaga** [comment]
> Protocol-less URLs are an anti-pattern (bad practise). It also means you wouldn't be able to Ctrl+click them in a code editor to launch the website in a browser.
> 
> Those URLs are all HTTPS-only so making the URLs explicitly HTTPS saves a redirect.

Okay, got it... so these websites are HTTPS Force enabled? So whenever I fire http it will convert to https is that right?

**Comment by WarenGonzaga** [comment]
Based on my research I agree let's do that... force to HTTPS... ;) @eltonmesquita let's add this on v4 please thanks!

**Pull request merged**
