### PR TITLE
Adds version without vendor prefixes for use with plugins like Autoprefixer

### PR DESCRIPTION
**Pull request by JohnnyWalkerDesign**
For users who are not using Grunt, but who are using another task manager like (eg. Gulp), a precompiled version without `-vendor-` prefixes is useful. I've added two new versions, one minified, one not.

### CODE REVIEW

**Comment by JohnnyWalkerDesign** [comment]
Tagging the conversation about this #482

**Comment by tnga** [comment]
It will be also good if you provide the gulp script; so contributors or tagged users can use it when necessary.

**Comment by JohnnyWalkerDesign** [comment]
That might be good, but the Gulpfile I used was a hacky mess really. I wouldn't share it.

**Comment by daneden** [comment]
We’re using Grunt (currently) and I’d expect to see these files generated automatically by the Gruntfile. I’m also not sure about the added benefit of adding this to the main project since autoprefixer can deal with the existing prefixes in the compiled CSS anyway. Closing this for now.

**Comment by JohnnyWalkerDesign** [comment]
Happy to see the vendor prefixes have been removed by default now!

**Pull request closed without merging**
