### PR TITLE
replace transform: none to transform: translate3d(0,0,0)

### PR DESCRIPTION
**Pull request by mpr0xy**
I find (in mobile) when fadeInRight down, the element touch event is not working and some absolute element disappeared if transform is none.

### CODE REVIEW

**Comment by imrealzohan** [comment]
same prob

**Comment by daneden** [comment]
You’ll have to change the files in `source` for this change to persist. Make that update and recompile, and I’ll happily merge!

**Comment by mpr0xy** [comment]
@daneden  I changed the files in `source` and recompiled

**Comment by daneden** [comment]
What’s the `./idea` file introduced on gitignore? And could you address the merge conflicts?

**Comment by mpr0xy** [comment]
@daneden  `.idea/`  directory is my IDEA editor generated

**Comment by eltonmesquita** [comment]
@mrp0xy, can you address the merge conflict? Would be good to have this fix on the next release.

**Pull request closed without merging**
