### PR TITLE
Update Builds 3.7.0

### PR DESCRIPTION
**Pull request by WarenGonzaga**
Hello, @daneden I manage to fix the conflicts... I am confused with the rebase where should I start. So I get the latest copy from you guys by using upstream. So let me know if this pull request is good?

* Minor Bug Fixes
* Updated Builds to 3.7.1
* Migrated from gulp.js 3.9.x to gulp.js 4.0.x

### CODE REVIEW

**Comment by daneden** [comment]
I don’t think there's any action required here actually @WarenGonzaga: I commented on #834 mentioning that your rebase to master seemed to fix conflicts and everything is working fine now. Looks like this PR just updates package-lock.json, which I don’t think is necessary here and I'd rather not cause thrash with another minor release.

**Comment by daneden** [comment]
@WarenGonzaga additionally, for future PRs you might consider forking again or updating from this repo's master branch since it looks like your pull requests are bringing a ton of old commits with them!

**Comment by WarenGonzaga** [comment]
@daneden can you please include in the 3.7.0 release that we are already in GULP.JS 4 :) you forgot it.

**Comment by WarenGonzaga** [comment]
Alright, @daneden will do it...

**Pull request closed without merging**
