### PR TITLE
simplifies code contributions by fully automating dev setup with Gitpod.

### PR DESCRIPTION
**Pull request by nisarhassan12**
Hi! :slightly_smiling_face: 

This PR simplifies code contributions by fully automating the setup with Gitpod( A free VS Code like 
IDE ). With a single click, it will launch a Ready-To-Code workspace with all the dependencies being pre-installed & the build script in process so that anyone interested in contributing can start straight away.

It seems to work well. You can give it a try on my fork of the repo via the link below: 

https://gitpod.io/#https://github.com/nisarhassan12/animate.css

image

### CODE REVIEW

**Comment by WarenGonzaga** [comment]
alright thanks for sharing!

**Comment by WarenGonzaga** [comment]
@nisarhassan12 gitpod support added... check #1029 

@eltonmesquita please close this...

**Comment by WarenGonzaga** [comment]
@daneden please review this thanks!

**Comment by daneden** [comment]
Frankly I feel like this adds some unnecessary overhead/undue preference. IMO, I’d rather keep the root repository clean of any proprietary config files (at least in v4 and onwards) or at least favour widely canonical tools such as GitHub actions or ESLint/Prettier vs. less canonical tools like Gitpod.

It sounds like we’ve already merged some of these changes in v4, but I’d like the opportunity to reevaluate. (I’ll try to reflect this stance in the contribution guidelines I’m working on in #1033)

**Pull request closed without merging**
