### PR TITLE
Rotation animations

### PR DESCRIPTION
**Pull request by yangshun**
Added `rotateClockwise` and `rotateCounterClockwise` animations. Personally I use this simple animation a lot and I was surprised to find that it was not already inside animate.css. It falls under attention seekers

I pushed the demo site onto my `gh-pages` branch. You may try it out here: [http://yangshun.im/animate.css/](http://yangshun.im/animate.css/)

### CODE REVIEW

**Comment by GochoMugo** [comment]
:+1: This would be useful

**Comment by tunnckoCore** [comment]
:+1:

**Comment by nemo** [comment]
:+1:

**Comment by yangshun** [comment]
@daneden could you have a look at this?

**Comment by daneden** [comment]
This doesn’t quite fall under the typical category of animate.css’s animations—I don’t think there are currently any infinitely-playing (by default) animations and I’d rather not introduce them.

**Pull request closed without merging**
