### PR TITLE
SASS version

### PR DESCRIPTION
**Pull request by ShahinSorkh**
I've made a SASS version from this package using the css version
I linked to my SASS version and cleaned your README.md

### CODE REVIEW

**Comment by rickerd** [comment]
@daneden why don't you accept this PR? It's a huge miss these scss files.

**Comment by eltonmesquita** [comment]
@rickerd, there's a sass version branch, which will be getting some attention soon and a release. Please see #277.

**Comment by rickerd** [comment]
I found it, thanks.

**Comment by WarenGonzaga** [comment]
Oh I see! the sass already updated,

**Comment by eltonmesquita** [comment]
@ShahinSorkh I'm closing this PR as the SASS branch will get some deserved attention, but feel free to collaborate to the discussion and send some PR's to the the branch.
See #277 .

**Comment by WarenGonzaga** [comment]
@eltonmesquita alright elton!

**Pull request closed without merging**
