### PR TITLE
Adding two speed classes

### PR DESCRIPTION
**Pull request by saidbakr**
To give more control for the animation speed.

### CODE REVIEW

**Comment by grantholle** [comment]
While we're at it... maybe add `fast` and `faster` classes too?

**Comment by eltonmesquita** [comment]
Thanks for the PR. This does make sense, but the `!important`s on it doesn't. Can you please solve it and take @grantholle comment in consideration? Although I think a faster option probably won't make any good as most of animations would lose their meaning...

**Comment by WarenGonzaga** [comment]
As I remember this is a suggestion from #813, I will submit a separate PR with updated code. I will consider the @grantholle suggestion.

**Comment by daneden** [comment]
Closing since this was addressed more comprehensively in #790.

**Pull request closed without merging**
