### PR TITLE
updated animateCSS function

### PR DESCRIPTION
**Pull request by adithyaanil1999**
so that one can use options while invoking eg: animateCSS(node,'fadeIn slower')

### CODE REVIEW

**Comment by adithyaanil1999** [comment]
Well currently, you cannot add multiple classes to the element right, I just addressed that so that one can use the 'slower','faster','fast',etc classes into the node, while also adding the animation classes. I also changes the parameter of the function so it receives the node name instead of the node name, but that is just my personal preference,that I used in my project.

**Comment by WarenGonzaga** [comment]
@eltonmesquita can you confirm this? so I can add it to the current development...

**Comment by adithyaanil1999** [comment]
Yes I have confirmed that it works and even used it in my portfolio website https://github.com/adithyaanil1999/Portfolio, it works as intended. All I did was use .split on animationName then subsequently used the ... (spread) operator to add the classes using classList.add(). I also changed back the function parameters in the last commit to be in line with the original (i.e the function receives the **node name** ie '_element_', rather than the node itself).

**Comment by WarenGonzaga** [comment]
@adithyaanil1999 thanks! Let's wait for @eltonmesquita to confirm this since he is the main collaborator here. I'm just a feature contributor here.

**Comment by eltonmesquita** [comment]
That function is just a small guidance of how you could use js to add the animations. I prefer to keep it simple and easier to understand. Thanks for the PR!

**Pull request closed without merging**
