### PR TITLE
"jello animation"

### PR DESCRIPTION
**Pull request by procodeing**
Makes elements have a kinda jellylike bounce, but the element has to have it's width defined, or be a block element and be inline.
[here is the pen](http://codepen.io/procodeing/pen/MwYZbQ/)

### CODE REVIEW

**Comment by yangshun** [comment]
I do not see any animation in the codepen..

**Comment by tunnckoCore** [comment]
> I do not see any animation in the codepen..

:+1: same here

**Comment by procodeing** [comment]
that is weird, not for me
http://codepen.io/procodeing/pen/MwwxGe

**Comment by procodeing** [comment]
????

**Comment by procodeing** [comment]
Wait I fixed it

**Comment by procodeing** [comment]
@yangshun  @tunnckoCore  I forgot to autoprefix

**Comment by procodeing** [comment]
:sweat_smile:

**Comment by yangshun** [comment]
Yep see it now! :+1:

**Comment by procodeing** [comment]
yay!

**Comment by tunnckoCore** [comment]
cool, looks great!

**Comment by procodeing** [comment]
thank you!

**Comment by xahid** [comment]
WOW Great

**Comment by procodeing** [comment]
thank you also

**Comment by procodeing** [comment]
while were waiting, Ive been making another, which you can see [here](https://github.com/procodeing/yolo_dangerzone)

**Comment by tunnckoCore** [comment]
and what is this? what's new?

**Comment by procodeing** [comment]
@tunnckoCore  In that one, It has a new "shiver" animation, along with the jello

**Comment by procodeing** [comment]
@tunnckoCore also, You can get A sneek peek at what im working on with the fork.

**Comment by daneden** [comment]
This is pretty nice! The initial stretch is a little over-the-top: maybe try dialling it down a bit?

**Comment by procodeing** [comment]
@danden sure, just give me a sec.

**Comment by procodeing** [comment]
@danden It will be a while, I have some work to do,besides the animation.

**Comment by procodeing** [comment]
@danden and done

**Comment by daneden** [comment]
Better! The first stretch is a little drawn-out now, though. It'd be great if it lasted for fewer frames. You’ll also need to rebase to the most recent commit on master.

**Comment by procodeing** [comment]
@daneden ok, give me about a day, then everything should be good, the animation a bit better and shorter, and rebased

**Comment by procodeing** [comment]
@daneden wait. My terminal is not being so friendly, and It wont fix the conflicts like usual, and I will have to find a fix

**Comment by procodeing** [comment]
@daneden actually, give me a little longer, I have a little bit of a load

**Comment by procodeing** [comment]
@daneden rebased the new and inproved animation, and made animate.min.css smaller on my pull by making the comment one line. It should be completly ready to merge now.

**Comment by daneden** [comment]
Perfect. Bear in mind that the Grunt task doesn’t make the comments one-line, so next build will break this. nbd. Merging!

**Comment by daneden** [comment]
@procodeing if you could open a new PR to add this animation to the gh-pages branch, that’d be great!

**Pull request merged**
