### PR TITLE
[New Animation] - specials/stamp

### PR DESCRIPTION
**Pull request by jcs090218**
I made a small animation, the purpose of this animation is to create the action like stamping.

Preview: https://codepen.io/JayCeS/pen/yQyZzL

### CODE REVIEW

**Comment by WarenGonzaga** [comment]
@eltonmesquita I think we can add this one... what do you think @daneden ?

**Comment by WarenGonzaga** [comment]
@eltonmesquita @daneden lets add this one on v4

**Comment by eltonmesquita** [comment]
Thanks for the PR @jcs090218 !
I think this one's a bit over and the motion feels unnatural. I don't know how this would fit in an interface.
Any opinion on this @daneden ?

**Comment by daneden** [comment]
Agreed, this feels pretty use-case specific and has some issues—scaling an element so large causes pixelation that we’d want to avoid.

**Comment by WarenGonzaga** [comment]
thanks guys for the review @daneden @eltonmesquita

**Pull request closed without merging**
